version: "3.3"
services:
  api:
    build: .
    ports:
      - "80:3333"
    links: 
      - db
  db:
    image: "mysql"
    restart: always
    ports:
      - 8080:8080
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: pi
      MYSQL_USER: pi
      MYSQL_PASSWORD: 12345678
    volumes:
      - /var/lib/postgres/data:/var/lib/postgresql/data/pgdata
