version: "3.3"
services:
  api:
    build: .
    ports:
      - "3333:3333"
    links: 
      - db
  db:
    image: "mysql"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: pi
      MYSQL_USER: pi
      MYSQL_PASSWORD: 12345678

